# Generated by Django 4.0.7 on 2023-06-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Idno', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
                ('Picture', models.FileField(upload_to='')),
            ],
        ),
    ]
