# Generated by Django 4.0.7 on 2023-06-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0002_uploaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
